name: Run every 24 hours
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Run npm install
      run: "npm install"

      - name: Run npm post
      run: "npm post"